services:
  #Build the client container for the website
  client: 
    container_name: client
    image: abbien/shark-frontend:v2.0.1
    build:
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
    networks:
      - trust.net

  #Build the backend container for my website
  backend: 
    container_name: backend
    image: abbien/shark-backend :v1.0.1
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 5000:5000
    environment:
      - mongodb://MONGO:27017/mydatabase
    networks:
      - trust.net
    
  #The database that will be assosiated with the website
  mongo:
    container_name: db
    image: mongo:4.4.20
    restart: always
    ports:
      - 27017:27017 
    volumes:
      -bluewaters:/data/db
    networks:
      - trust.net

#Declare the volume that the database will be using to persiste the data
volumes:
  bluewaters:/data/db: 
    driver: local
#create bridge network for the container to communicate
networks:
  trust.net:
    driver: bridge