
- name: Pull website image from repository
  docker_image:
    name: abbien/shark-backend :v1.0.1
    source: pull

- name: Launch backend Container
  docker_container:
    name: abbien/shark-backend :v1.0.1
    image: abbien/shark-backend :v1.0.1
    networks:
      - name: trust.net
    ports:
      - "5000:5000" 
    command: "npm start"
  become: true